FROM golang:1.22 AS builder
WORKDIR /build
COPY ../ .
RUN make lint
RUN make test

FROM traefik:v3.2
WORKDIR /
RUN mkdir -p plugins-local/src/github.com/danbiagini/traefik-cloud-saver
COPY ../ plugins-local/src/github.com/danbiagini/traefik-cloud-saver/
COPY test/traefik.yml /etc/traefik/traefik.yml

COPY test/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
