linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused

run:
  deadline: 5m
  go: '1.22'  # Matches your Go version

# Basic settings for the enabled linters
linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true

# Ignore certain issues if needed
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
