displayName: Cloud Saver
type: provider
iconPath: .assets/icon.png

import: github.com/danbiagini/traefik-cloud-saver

summary: 'Save cloud resource costs by automatically stopping instances that are not being used.
Think of it like "turning the lights off when the room is empty."'

testData:
  windowSize: 1m  # 1 minute, how often to check for unused resources
  metricsURL: http://localhost:8080/metrics  # URL of the metrics endpoint (Prometheus)
  apiURL: http://localhost:8080/api  # URL of the Traefik API
  trafficThreshold: 1  # requests per windowSize before scaling down
  debug: true  # enable debug logging
  cloudConfig:
    type: gcp 
    zone: "Change to your zone"
    region: "Change to your region"
    projectID: "Change this to your GCP project ID or not needed with service account json file"
    credentials:
      secret: "Change this to a valid service account json file path and change the type to service_account"
      type: token

